### PR TITLE
Feature/86cv686va combine message conversation and inbox components

### PR DESCRIPTION
**Pull request by viggy21**
Combined the message conversation and inbox components so that when you click on a message preview (on the left), you'll see the corresponding message conversation (on the right). 
Note: there is a bug when you send a message in one conversation, it appears in the other conversation but this will be corrected in the 'send feature' branch that will implement the send message functionality.

### CODE REVIEW

**Review by RyanAHicks — CHANGES_REQUESTED** [review]
Needs to be rebased with develop as App.jsx is currently behind.

**Comment by viggy21** [comment]
Branch has been rebased

**Comment by viggy21** [comment]
Removed lines 37-110 from App.jsx

**Review by RyanAHicks — APPROVED** [review]
Clicking on a message preview shows the conversation. Works as intended and looks good! Understand that the bug will be fixed in another branch. Ready to merge!

**Pull request merged**
