### PR TITLE
Feature/86cuwgqp0 payment detail on artist profile

### PR DESCRIPTION
**Pull request by CameronNguyen0**
Payment details tab implemented on artists profile setting
https://app.clickup.com/t/86cuwgqp0

### CODE REVIEW

**Comment by hiri45** [comment]
The add payment page shows up fine and it saves fine, however the account name can take numbers, the bsb is in the format xxx-xxx however when I'm able to put just 1 number and it is able to save. Also the account number can take up to any amount of numbers. If there can be some requirements for the placeholders for example the account name can't take numbers etc.

**Comment by hiri45** [comment]
feature/86cve5tfk uses the exact requirements needed for payment details. :)

**Comment by CameronNguyen0** [comment]
Hi @hiri45, the changes have been made, can u check it again ?

**Review by hiri45 — APPROVED** [review]
everything works as intended

**Pull request merged**
