### PR TITLE
Feature/86cuvrrfp delete gallery post

### PR DESCRIPTION
**Pull request by scp777**
**Ticket:**
https://app.clickup.com/t/86cuvrrfp

**Feature Description:**
Artist can delete photo from their gallery. 

**Instructions:**
1. Create an artist account with username/alias as: abcd1234A
2. Login as abcd1234A
3. Find "HOW TO IMPORT.md" and import:
- mongoimport -h localhost:3001 --db meteor --collection images --file mockdata/galleryImages50_abc.json --jsonArray
- mongoimport -h localhost:3001 --db meteor --collection posts --file mockdata/post50_abc.json --jsonArray
4. Click on an image in the gallery tab and then click the delete button.
5. Confirm delete.
6. Photo should now be removed from the gallery (the post in the database is also removed).

**Results**
Screenshot 2024-08-17 at 3 22 08 PM
Screenshot 2024-08-17 at 3 22 15 PM
Screenshot 2024-08-17 at 3 22 20 PM
Screenshot 2024-08-17 at 3 22 27 PM

### CODE REVIEW

**Review by hiri45 — APPROVED** [review]
works as intended

**Comment by hiri45** [comment]
please resolve conflicts on this branch

**Comment by scp777** [comment]
Hi! Merge conflicts should not be resolved, let me know if issues persist and I'll take another look - thank you :)

**Review by hiri45 — APPROVED** [review]
works and everything looks good

**Pull request merged**
