### PR TITLE
Feature/86cuvrq0c: user signup pages

### PR DESCRIPTION
**Pull request by RyanAHicks**
Completed ticket number: https://app.clickup.com/t/86cuvrry3

To check, please go to: http://localhost:3000/register

The user should firstly select Account Type (Bride or Artist).

Secondly, the user should enter details to create an account - username, name, email, password, retype password.

Username and email must be unique (can't enter the same username and/or email to make multiple accounts).
Ensure password adheres to validation requirements.
Ensure retype-password matches password.
Thirdly, enter the 6-digit code (NOTE: email API not yet implemented - enter any 6 digits for now)

Fourthly, account has been signed up, can return the login page.

### CODE REVIEW

**Review by kbib0002 — DISMISSED** [review]
All changed files have passed code review.

However, please do add more comments to your files in future.

**Review by NikkiShao — DISMISSED** [review]
Looks good

**Review by NikkiShao — APPROVED** [review]
Changes looks good

**Review by NikkiShao — APPROVED** [review]
Looks good

**Pull request merged**
