### PR TITLE
Feature/86cvc78qg-86cvc786k payment confirm modal & confirmation page

### PR DESCRIPTION
**Pull request by nethbtju**
This ticket follows the http://localhost:3000/payment-details flow but it needs PR https://github.com/Monash-FIT3170/Behind-The-Veil/pull/44 to be approved first and rebased.

### CODE REVIEW

**Review by RyanAHicks — APPROVED** [review]
Looks good! Payment confirmation ui well presented.

**Review by RyanAHicks — CHANGES_REQUESTED** [review]
Needs to be rebased with develop, currently has conflicts in App.jsx and PaymentDetails.jsx

**Comment by nethbtju** [comment]
Rebased, please rerun to make sure all functionality is present from your end

**Review by kbib0002 — APPROVED** [review]
Adherence to coding conventions is good.

Functionality is as expected - **return to account** button now works.

UI is as expected.

**Pull request merged**
