### PR TITLE
Feature/86cw8tck7 dashboard total revenue

### PR DESCRIPTION
**Pull request by scp777**
**Ticket:**
https://app.clickup.com/t/86cw8tck7

Revenue total will update dynamically based on artist booking database.

**Instructions:**
1. Create an artist account with username/alias as: abcd1234A
2. Login as abcd1234A
3. Find "HOW TO IMPORT.md" and import:
- mongoimport -h localhost:3001 --db meteor --collection bookings --file mockdata/booking_user1000.json --jsonArray
4 Go to the artist dashboard tab in artist profile page

**Results:**
Screenshot 2024-08-17 at 4 58 20 PM

### CODE REVIEW

**Comment by hiri45** [comment]
please resolve conflicts

**Comment by scp777** [comment]
Hi! Merge conflicts should not be resolved, let me know if issues persist and I'll take another look - thank you :)

**Comment by hiri45** [comment]
there are still some merge conflicts please resolve when you get the chance :)

**Comment by scp777** [comment]
conflicts resolved :)

**Review by kbib0002 — APPROVED** [review]
Functionality works correctly - managed to replicate the steps outlined in the PR and achieved the same results.

User interface looks as expected.

**Pull request merged**
