### PR TITLE
Feature/86cuxgccy forgot password + login logic

### PR DESCRIPTION
**Pull request by NikkiShao**
Added forgot password logic and UI
- initial forgot password page to enter email
- checks if valid email/if user exists (does not actually send email, waiting for email API setup)

- directs to change password page (for demo purposes - as if user clicked on change password link)
 - has new password verification (up to standards, of capital+lowercase+number+symbol+min 8 letters)

- directs to final password changed confirmation page

Edited Login and Register CSS and logic
- made CSS tailwind style
- updated the register logic to match meteor accounts package and the Figma design
- Login is functional

### CODE REVIEW

**Review by kbib0002 — CHANGES_REQUESTED** [review]
LoginRegister Visual is not appearing as expected!


Screenshot 2024-05-15 at 16 12 27

**Comment by kbib0002** [comment]
Adherence to coding standards is fantastic.

Forgot Password journey looks good; all pages have functionality working as expected and the UI is consistent.

**Comment by NikkiShao** [comment]
Completely fixed visual moving issue. Should now only scale as screen size smaller but not move up and down.

**Review by kbib0002 — APPROVED** [review]
Login/Register Visual working as expected.

**Pull request merged**
