### PR TITLE
Feature/86cvdmb26 overall css consistency

### PR DESCRIPTION
**Pull request by NikkiShao**
1. Updated mock data guide and data to match the accounts package - edited and ready for demo.
2. Refactored artist profile, 
 - each tab into its own components
 - the top buttons now move more dynamically (if the page is small enough one goes into the row above)
image
image
image

3. edited pagination number of items to be drop down rather than free numbers
image

4. added a non-existing page for any non-routed paths (rather than a hard redirect to home page which might be confusing) 
image

5. General CSS related for the booking flow
  - Edited service header to have either DATE or TYPE [image below]
  - minor CSS for the calendar, select start time buttons, "No available times" text
  - check location is not empty when submitting
  - tooltip background made same glass-base as all other panels, no longer as see-through
image

6. Updated specific services page reactive to mock database data and dynamic to different screen sizes
image
image

7. Overall restructuring of both user profile pages to be consistent with each other
  - edited the profile display component and used it for both artist and brides
  - added pagination to all booking and services views for the profiles [image below]
  -  created new enums for service filters to match with the booking filters already there
  - changed the mockdata used by brides
  - Made the bride profile for bookings also use the same BookingCards and BookingListView that is already there to match with the artist profile
image

8. Created booking status display component (that also includes a tool tip)
image

9. Minor fixes
- another fix for login visual for the long register page (hopefully it's actually completely fixed this time)
- using defaultValue instead of selection for dropdowns for good practice (and because it gave me a warning for it)
- added some "key" for most list objects (because it also gave me some warnings)
- moved enums all unto enums folder
- other minor CSS changes such as using `"wordBreak": "break-word"` to break long words but not every word for the WHOLE APP (so I edited message part which had redundant code for it)

### CODE REVIEW

**Comment by kbib0002** [comment]
Images on the booking cards on the Brides Profile page do not appear correctly.
Screenshot 2024-05-19 at 09 11 44

**Comment by kbib0002** [comment]
All images across the website, in fact, are not displaying after signing in as a Bride.
Screenshot 2024-05-19 at 09 13 58

**Review by RyanAHicks — DISMISSED** [review]
Changes look fantastic! Everything ui related is much more consistent. source code optimisations look good as well.

Here are the only couple of things I found.

1. When adjusting the webpage size horizontally, just before it turns into mobile view the navigation bar ends up clipping the text in a weird way (see photo below).

Screenshot 2024-05-19 at 1 38 26 pm

2. Same clipping issue for the artist profile tabs, this happens just before the website turns into mobile view (see photo below).

Screenshot 2024-05-19 at 2 09 15 pm

3. Total customers - Lifetime & This Month are centred, while Total earnings and Pending earnings appear to be justified to the left (see photo below). 

Screenshot 2024-05-19 at 2 09 28 pm

(I know these are little things haha, if we're not worried about these minor things I approve of the pr otherwise!)

**Review by nethbtju — APPROVED** [review]
Approved merge

**Pull request merged**
